/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [],
  docsSidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "link",
      label: "Releases",
      href: "/blog",
    },
  ],
};

module.exports = sidebars;
